feat(deps): auto-update vendorHash

diff --git a/.github/workflows/nix-build.yml b/.github/workflows/nix-build.yml
--- a/.github/workflows/nix-build.yml
+++ b/.github/workflows/nix-build.yml
@@ -19,6 +19,7 @@ jobs:
     if: github.event.pull_request.draft == false
     permissions:
       pull-requests: write
+      contents: write
     strategy:
       fail-fast: false
       matrix:
@@ -55,9 +56,10 @@ jobs:
         run: |
           nix build \
             "github:soulwhisper/nix-config#ciSystems.${{ matrix.system }}" \
+            --profile ./profile \
             -v \
             --log-format raw \
-            --profile ./profile
+             > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)
 
       - name: Build new ${{ matrix.system }} system
         run: |
@@ -70,15 +72,19 @@ jobs:
             --log-format raw \
              > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)
 
-      - name: Output build failure
+      - name: Update vendorHash
+        id: vendorhash
         if: failure()
-        run: |
-          drv=$(grep "For full logs, run" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
-          if [ -n $drv ]; then
-            nix log $drv
-            echo $drv
-          fi
-          exit 1
+        run: bash scripts/update_vendorhash.sh
+
+      - name: add & commit vendorHash
+        if: failure()
+        uses: EndBug/add-and-commit@v9.1.4
+        with:
+          add: 'pkgs/_sources/vendorhash.json'
+          author_name: soulwhisper
+          author_email: soulwhisper@outlook.com
+          message: 'chore(deps): update vendorHash'
 
       - name: Diff profile
         id: diff
@@ -117,3 +123,5 @@ jobs:
       - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
         name: Check matrix status
         run: exit 1
+# todo
+# add job(matrix-failed), collect build-failure-logs, update vendorhash.
